### PR TITLE
Add non-interactive commands on ironic-oneview-cli

### PR DESCRIPTION
**Pull request by hugonicodemos**
The following commands are now available for noninteractive use:

- server-profile-template-list
- server-hardware-list
- flavor-create
- node-create

### CODE REVIEW

**Comment by ricardoas** [comment]
Two more cases with weird messages:

**Creating flavor for invalid node UUID**

```
root@aio1-utility-container-8f2a3690:~# ironic-oneview --insecure flavor-create --node fs8e3a73-7e76-4c3d-a5fb-3213b3f622ac --name vish
It was not possible to find the element fs8e3a73-7e76-4c3d-a5fb-3213b3f622ac.
```
_Action: change to user friendly message, e.g.: "Could not find an Ironic Node matching 'd03c7d03-8bac-4ccb-a051-c11ba5acda64'"_

-------------

**Creating flavor without specifying node UUID**

```
root@aio1-utility-container-8f2a3690:~# ironic-oneview --insecure flavor-create --name vish
The parameter --node needs to be present when --name is used.
```
_Action: change to user friendly message, e.g.: "It is mandatory to specify an Ironic Node for flavor creation. Use --node <uuid>"_

**Comment by ricardoas** [comment]
Message for **Creating node with non-matching server profile** is not yet as expected!

**Comment by SauloAislan** [comment]
Another scenario for creating flavor:

**Creating flavor for invalid node UUID without any Ironic nodes**

```ironic-oneview --insecure flavor-create --node fs8e3a73-7e76-4c3d-a5fb-3213b3f622ac --name vish```

Message:
No Ironic nodes running OneView drivers were found. Please, create a node to be used as base for the flavor.

Ironic Oneview CLI to Openstack Ocata that's OK.

**Comment by SauloAislan** [comment]
Creating node with invalid MAC without passing value Server Profile Template and Server Hardware

```ironic-oneview node-create --classic -m uhuhuh```

Action: Check the MAC is valid before list Server Profile Template.

Message: The node could not be created. 'uhuhuh' is not a valid MAC address.

**Pull request merged**
